create database retail;
use retail;

# Task:1 create table based on ERD

create table brands(
brand_id int primary key,
brand_name varchar(50));

create table categories(
category_id int primary key,
category_name varchar(50));

create table customers(
customer_id int primary key,
first_name varchar(50),
last_name varchar(50),
phone_no varchar(50),
email varchar(50),
street varchar(50),
city varchar(50),
state varchar(50),
zipcode varchar(50));

create table orders(
order_id int primary key,
customer_id int,
order_status int,
order_date varchar(50),
required_date varchar(50),
shipped_date varchar(50),
store_id int,
staff_id int,
foreign key (customer_id) references customers(customer_id));


create table order_items(
order_id int,
item_id int,
product_id int,
quantity int,
list_price float,
discount decimal(5,4),
total_sale float,
foreign key (order_id) references orders(order_id),
foreign key (product_id) references products(product_id));

# Queries to change the string to date format.
select * from orders;
update orders set shipped_date = str_to_date(shipped_date, '%d-%m-%Y');
alter table orders modify shipped_date date;

set sql_safe_updates=0;


create table products(
product_id int primary key,
product_name varchar(100),
brand_id int,
category_id int,
model_year varchar(5),
list_price float,
foreign key(category_id) references categories(category_id),
foreign key (brand_id) references brands(brand_id));


create table order_items(
order_id int,
item_id int,
product_id int,
quantity int,
list_price float,
discount decimal(5,4),
foreign key (product_id) references products(product_id));

create table staffs(
staff_id int primary key,
first_name varchar(50),
last_name varchar(50),
phone_no varchar(50),
email varchar(50),
active int,
store_id int,
manager_id int,
foreign key (store_id) references stores(store_id));

create table stores(
store_id int primary key,
store_name varchar(50),
phone varchar(50),
email varchar(50),
street varchar(50),
city varchar(50),
state varchar(50),
zip_code varchar(10));

create table stocks(
store_id int,
product_id int,
quantity int,
foreign key (store_id) references stores(store_id),
foreign key (product_id) references products(product_id));

# task 2 Import CSVs into SQL - Completed

# task 3 Inner Join for Order_details - Orders, Order_items and Products to display line items

select 
 oi.order_id,
 oi.item_id,
 oi.product_id, 
 p.product_name, 
 c.category_id, 
 c.category_name, 
 oi.quantity, 
 oi.list_price,
 oi.discount from order_items oi
inner join products p on oi.product_id=p.product_id 
inner join categories c on p.category_id=c.category_id;

#task 4 Total sales by store - Write a query to group sales (total_price) by each store_id

select s.store_id, sum(oi.total_sale) as total_sales from order_items oi 
inner join orders o on oi.order_id=o.order_id inner join stores s on o.store_id=s.store_id group by s.store_id;

#task 5 Top 5 selling products - Use ORDER BY and Limit  to get the top 5 most sold products by quantity.

select p.product_name, sum(oi.quantity) as quantity from order_items oi 
inner join products p on oi.product_id=p.product_id group by p.product_name order by quantity desc limit 5;  

# Task 6 Customer purchase summary - For each customer, return total orders placed, total items purchased, and total revenue.

select 
c.customer_id, 
c.first_name, 
c.last_name, 
count(distinct o.order_id) as total_orders,
sum(os.quantity) as total_items,
sum(os.total_sale) as total_revenue
from customers c
left join orders o on c.customer_id=o.customer_id
left join order_items os on o.order_id=os.order_id group by c.customer_id;

# Task 7 Segment customers by total spend - write a query to classify customers into spending brackets (e.g low,medium,high)
# below or = 1000 -> low, above 1000 - 4000 medium, above 4000 high.

select c.first_name, c.last_name, sum(os.total_sale) as total_spending,
case
  when sum(os.total_sale) <=1000 then "Low"
  when sum(os.total_sale) between 1001 and 4000 then "Medium"
  else "High"
  end as spending_segment from customers c 
inner join orders o on c.customer_id=o.customer_id 
inner join order_items os on o.order_id=os.order_id 
group by c.first_name, c.last_name;

# Task 8 Staff Performamce analysis - Analyze total revenue generated by each staff member based on their handled orders

select s.staff_id,s.first_name, s.last_name, sum(oi.total_sale) as Total_Revenue from order_items oi 
join orders o on oi.order_id=o.order_id 
join staffs s on o.staff_id=s.staff_id group by s.first_name, s.last_name,s.staff_id;

# Task 9 Stock Alert Query - Write a query to list products where stock quantity < 10 in any store

select s.product_id, p.product_name, s.quantity, s.store_id from products p
right join stocks s on p.product_id=s.product_id where s.quantity <10;

# task 10 - create final segmentation table - create a table customer_segments that will be populated from python ML results later

create table customer_segment (
segment_id int auto_increment primary key,
customer_id int not null,
recency int,
frequency int,
monetary decimal(10,2),
segment_group varchar(50),
run_date date,
foreign key (customer_id) references customers(customer_id));
alter table customer_segment drop column run_date;
select * from customer_segment;

